import {useState} from "react";
import {ArrowLeft,Camera,ChevronRight,Cookie,FileText,Mail,Scale,ShieldCheck,Ticket,WalletCards,X} from "lucide-react";

const docs=[
  {id:"privacy",icon:ShieldCheck,title:"Privacy Policy",text:[
    ["1. Titolare del trattamento","Il Titolare del trattamento è Infinity Events SRL, con sede in Piazzale Don Enrico Paglioni, 1. Per richieste relative alla protezione dei dati personali è possibile contattare il Titolare all’indirizzo infinityeventsit@gmail.com."],
    ["2. A chi si applica","La presente informativa riguarda i trattamenti effettuati attraverso Infinity EventOS e le funzionalità collegate alla gestione degli eventi VividFest, quando l’utente utilizza l’area riservata, le funzioni di gestione del ticket, l’accesso all’evento, la gestione dei braccialetti o i servizi di reportistica."],
    ["3. Dati personali trattati","Possono essere trattati, in relazione alle funzionalità utilizzate, nome, cognome, indirizzo email e data di nascita; identificativi dell’account e dati tecnici necessari all’autenticazione e alla sicurezza; informazioni relative a ticket, stato del ticket, festival associato e registrazione dell’ingresso; identificativi del braccialetto NFC e informazioni di associazione quando la funzione è utilizzata; dati necessari per assistenza e gestione delle richieste."],
    ["4. Dati di autenticazione","L’accesso all’area riservata può utilizzare Firebase Authentication e i relativi meccanismi tecnici di autenticazione. Infinity EventOS utilizza i dati necessari per riconoscere l’account, autorizzare l’accesso alle funzioni e mantenere la sicurezza della piattaforma."],
    ["5. Finalità del trattamento","I dati sono trattati per creare e gestire gli account; amministrare festival, ticket e partecipanti; verificare i titoli di ingresso; registrare gli accessi; associare e gestire i braccialetti NFC quando previsti; fornire assistenza; mantenere la sicurezza e il corretto funzionamento del servizio; produrre e inviare report operativi agli utenti autorizzati; adempiere agli obblighi previsti dalla legge e tutelare i diritti del Titolare."],
    ["6. Biglietti e pagamenti","I biglietti VividFest sono nominativi. La vendita, il checkout e i relativi pagamenti sono gestiti tramite Ciaoticket. Infinity EventOS può ricevere o trattare esclusivamente le informazioni necessarie alla gestione operativa del ticket e dell’accesso, secondo i ruoli e le responsabilità effettivamente applicabili ai servizi utilizzati."],
    ["7. Braccialetti NFC","Quando il sistema NFC è attivo, l’identificativo del braccialetto può essere associato a un ticket, a un festival e/o a un account per permettere l’attivazione e la gestione operativa. L’eventuale introduzione di funzionalità cashless o di pagamento tramite braccialetto comporterà una verifica e, se necessario, un aggiornamento dell’informativa prima dell’attivazione."],
    ["8. Foto e video","Durante gli eventi possono essere effettuate fotografie e riprese video da operatori incaricati. I contenuti possono essere utilizzati per documentare e comunicare gli eventi sui canali ufficiali, inclusi sito web e social network. Per maggiori informazioni consultare il documento dedicato a Foto e video presente in questo Legal Center."],
    ["9. Report e comunicazioni","Gli utenti autorizzati possono ricevere report periodici relativi all’andamento e all’attività di un evento. I report operativi non costituiscono newsletter commerciale e, secondo la configurazione attuale, non utilizzano sistemi di tracciamento dell’apertura o dei click. La reportistica può essere disattivata secondo le funzioni disponibili."],
    ["10. Fornitori e infrastruttura","La piattaforma può utilizzare fornitori tecnologici per autenticazione, infrastruttura applicativa, database, invio email e servizi necessari all’erogazione delle funzionalità. I ruoli di Titolare, Responsabile o altro soggetto coinvolto devono essere determinati in base ai singoli servizi e ai relativi accordi applicabili."],
    ["11. Trasferimenti e servizi esterni","Alcuni fornitori tecnologici possono trattare dati al di fuori dell’Italia o dello Spazio Economico Europeo. Prima della pubblicazione definitiva di questa informativa devono essere verificati i fornitori effettivamente utilizzati, le localizzazioni dei dati e gli eventuali meccanismi di trasferimento previsti dalla normativa."],
    ["12. Conservazione","I dati sono conservati per il periodo necessario alle finalità per cui sono stati raccolti e, quando previsto, per adempiere a obblighi legali, contabili, fiscali o per l’accertamento e la tutela di diritti. I periodi di conservazione specifici devono essere definiti nella documentazione interna di Infinity Events in funzione del singolo trattamento."],
    ["13. Cancellazione dell’account","L’utente può richiedere la cancellazione del proprio account. La richiesta viene gestita manualmente entro 3–4 giorni lavorativi. La cancellazione non comporta necessariamente l’eliminazione immediata di dati che devono essere conservati per legge o che siano necessari alla tutela di diritti."],
    ["14. Diritti dell’interessato","L’interessato può esercitare, nei casi previsti, i diritti di accesso, rettifica, cancellazione, limitazione del trattamento, opposizione e portabilità, oltre agli altri diritti riconosciuti dalla normativa applicabile. Le richieste possono essere inviate a infinityeventsit@gmail.com."],
    ["15. Reclamo","Resta fermo il diritto di proporre reclamo all’autorità di controllo competente, secondo quanto previsto dalla normativa applicabile."],
    ["16. Aggiornamenti","La presente informativa può essere modificata quando cambiano funzionalità, fornitori, finalità o modalità di trattamento. La versione pubblicata nel Legal Center rappresenta la versione informativa resa disponibile attraverso la piattaforma."]
  ]},
  {id:"cookies",icon:Cookie,title:"Cookie Policy",text:[
    ["1. Ambito","Questa policy descrive l’utilizzo di cookie e tecnologie analoghe sui servizi web collegati a Infinity EventOS, per quanto applicabile alla configurazione effettivamente in uso."],
    ["2. Strumenti non utilizzati","Secondo la configurazione attuale, Infinity EventOS non utilizza Google Analytics, Meta Pixel o altri strumenti di analisi o profilazione pubblicitaria."],
    ["3. Tecnologie necessarie","Il sito e l’area riservata possono utilizzare cookie, local storage, token o tecnologie analoghe strettamente necessarie per autenticazione, sicurezza, gestione della sessione, preferenze tecniche e funzionamento delle funzionalità richieste dall’utente."],
    ["4. Finalità tecniche","Le tecnologie necessarie permettono, ad esempio, di mantenere una sessione autenticata, riconoscere l’utente, proteggere le richieste e consentire il funzionamento delle pagine riservate. Non sono utilizzate, nella configurazione attuale, per creare profili pubblicitari dell’utente."],
    ["5. Servizi di terze parti","I servizi di autenticazione e infrastruttura utilizzati dall’applicazione possono implementare propri meccanismi tecnici. L’elenco definitivo e aggiornato deve essere verificato rispetto alla configurazione di produzione e alla documentazione dei singoli fornitori."],
    ["6. Strumenti non necessari","Qualora in futuro venissero introdotti strumenti di analytics, marketing, advertising, profilazione o altre tecnologie non strettamente necessarie, saranno effettuate le verifiche richieste dalla normativa e, quando necessario, verrà introdotto un sistema di consenso prima dell’attivazione."],
    ["7. Aggiornamenti","La presente policy sarà aggiornata in caso di introduzione o modifica di cookie e tecnologie analoghe."]
  ]},
  {id:"terms",icon:Scale,title:"Termini e condizioni",text:[
    ["1. Oggetto","Infinity EventOS è una piattaforma software destinata alla gestione operativa di eventi e delle relative attività organizzative. Le funzionalità disponibili possono cambiare in base al ruolo dell’utente e al festival selezionato."],
    ["2. Accesso","Le funzioni riservate sono accessibili esclusivamente agli utenti autorizzati. L’utente non deve condividere credenziali o utilizzare account appartenenti ad altre persone."],
    ["3. Dati forniti","L’utente deve fornire dati corretti, aggiornati e veritieri quando richiesto. Se rileva un errore nei propri dati deve comunicarlo o correggerlo attraverso gli strumenti disponibili."],
    ["4. Utilizzo consentito","La piattaforma deve essere utilizzata esclusivamente per finalità lecite e coerenti con il ruolo assegnato. È vietato tentare di aggirare i controlli di sicurezza, accedere a dati non autorizzati, alterare dati, interferire con il funzionamento del servizio o utilizzare la piattaforma per attività fraudolente."],
    ["5. Disponibilità","Infinity Events SRL adotta misure ragionevoli per mantenere il servizio operativo, ma non garantisce la disponibilità continua e ininterrotta. Possono verificarsi manutenzioni, aggiornamenti, guasti, indisponibilità di servizi di terzi o altre circostanze tecniche."],
    ["6. Sicurezza","Eventuali vulnerabilità, accessi anomali o problemi di sicurezza devono essere segnalati tempestivamente a infinityeventsit@gmail.com. L’utente deve custodire le proprie credenziali e informare il Titolare se sospetta un accesso non autorizzato."],
    ["7. Proprietà intellettuale","Software, interfacce, marchi, testi, grafiche, loghi e altri contenuti di Infinity EventOS o dei relativi titolari sono protetti dalla normativa applicabile. Salvo autorizzazione, non è consentita la riproduzione, distribuzione, modifica o utilizzazione al di fuori delle finalità autorizzate."],
    ["8. Servizi di terzi","Alcune funzioni dipendono da servizi esterni, tra cui autenticazione, infrastruttura, email, ticketing e pagamenti. La disponibilità e le condizioni di tali servizi possono dipendere dai rispettivi fornitori."],
    ["9. Sospensione","In caso di uso non autorizzato, violazione delle regole o rischio per la sicurezza, l’accesso può essere limitato o sospeso nei limiti consentiti e necessari."],
    ["10. Contatti","Per assistenza, segnalazioni o richieste relative alla piattaforma: infinityeventsit@gmail.com."]
  ]},
  {id:"tickets",icon:Ticket,title:"Biglietti, vendita e rimborsi",text:[
    ["1. Vendita dei biglietti","I biglietti VividFest sono nominativi. La vendita, la procedura di acquisto, il checkout e il pagamento sono gestiti tramite Ciaoticket. Le condizioni specifiche mostrate da Ciaoticket durante l’acquisto costituiscono parte delle condizioni applicabili alla transazione."],
    ["2. Dati del ticket","Infinity EventOS può ricevere e utilizzare le informazioni necessarie per riconoscere il ticket, associarlo al festival e gestire le operazioni di accesso. Il ticket può essere collegato ai dati dell’account secondo le funzionalità disponibili."],
    ["3. Validità e accesso","Il ticket deve essere valido e utilizzabile secondo le condizioni dell’evento. All’ingresso possono essere effettuati controlli sul titolo di accesso e, quando previsto, sulla corrispondenza con il nominativo."],
    ["4. Richiesta di rimborso","La richiesta di rimborso è ammessa, secondo la regola attualmente prevista per l’evento, fino alle ore 00:00 del giorno di inizio dell’evento. Le modalità tecniche di richiesta, verifica ed erogazione del rimborso sono quelle rese disponibili da Ciaoticket, che gestisce la vendita e il pagamento."],
    ["5. Annullamento o rinvio","In caso di annullamento, rinvio, modifica sostanziale o altra variazione dell’evento, saranno comunicate agli acquirenti le procedure applicabili e le eventuali modalità di rimborso o utilizzo del titolo, anche attraverso Ciaoticket."],
    ["6. Doppio utilizzo o alterazione","Un ticket già utilizzato, contraffatto, alterato, duplicato o non valido può essere rifiutato. Eventuali contestazioni devono essere gestite attraverso i canali indicati dall’organizzazione e/o dal gestore della vendita."],
    ["7. Assistenza","Per problemi relativi all’acquisto o al pagamento, il primo riferimento operativo è il canale di assistenza indicato da Ciaoticket per la relativa transazione. Per problemi relativi all’accesso o alla gestione del ticket in Infinity EventOS è possibile contattare infinityeventsit@gmail.com."]
  ]},
  {id:"access",icon:FileText,title:"Regolamento di accesso",text:[
    ["1. Titolo di ingresso","L’accesso all’evento è consentito esclusivamente ai soggetti muniti di un titolo di ingresso valido secondo le condizioni dell’evento."],
    ["2. Ticket nominativo","Quando previsto, il personale può richiedere un documento idoneo a verificare la corrispondenza tra il nominativo indicato sul ticket e la persona che richiede l’accesso."],
    ["3. Controlli di sicurezza","L’organizzazione e il personale autorizzato possono effettuare i controlli di sicurezza previsti per l’evento e verificare validità, stato e utilizzo del titolo di ingresso. Il rifiuto di sottoporsi ai controlli può comportare il mancato accesso nei limiti consentiti dalle regole dell’evento e dalla normativa applicabile."],
    ["4. Ticket non valido","Un ticket già utilizzato, contraffatto, alterato, duplicato, acquistato attraverso canali non autorizzati o comunque non valido può comportare il rifiuto dell’ingresso."],
    ["5. Comportamento","La permanenza nell’area dell’evento richiede il rispetto delle indicazioni del personale, delle regole di sicurezza, delle disposizioni dell’organizzazione e delle norme applicabili. Comportamenti pericolosi, violenti o incompatibili con la sicurezza possono comportare l’allontanamento."],
    ["6. Braccialetti","Quando previsti, i braccialetti NFC possono essere utilizzati come identificativo operativo e associati al partecipante o al ticket. Non devono essere ceduti o manomessi quando ciò comprometta la validità o la sicurezza del sistema."],
    ["7. Cashless","Eventuali funzioni cashless o di pagamento tramite braccialetto non sono automaticamente comprese nel presente regolamento. Prima della loro attivazione saranno pubblicate le condizioni specifiche e le informazioni necessarie."],
    ["8. Regole specifiche","L’organizzazione può pubblicare ulteriori regole relative a singoli eventi, aree, orari, oggetti vietati, sicurezza e modalità di accesso. In caso di conflitto, si applicano le disposizioni specifiche comunicate per l’evento nei limiti previsti dalla legge."]
  ]},
  {id:"media",icon:Camera,title:"Foto e video",text:[
    ["1. Riprese durante gli eventi","Durante gli eventi organizzati da Infinity Events possono essere realizzate fotografie, video e altre registrazioni audiovisive da parte di operatori incaricati o autorizzati."],
    ["2. Finalità","Le riprese possono essere utilizzate per documentare gli eventi, raccontare le attività dell’organizzazione e realizzare contenuti di comunicazione e promozione sui canali ufficiali, inclusi sito web e social network come Instagram."],
    ["3. Riprese ambientali","In un evento aperto al pubblico possono essere realizzate riprese generali dell’ambiente, del pubblico e delle attività in corso. La presenza nell’area dell’evento può quindi comportare la possibilità di essere incidentalmente ripresi nell’ambito di tali contenuti."],
    ["4. Soggetti principali","Quando una persona viene individuata come soggetto principale di un contenuto, ad esempio per un’intervista o una registrazione dedicata, saranno adottate le modalità informative e autorizzative ritenute appropriate rispetto alla natura del contenuto e alla normativa applicabile."],
    ["5. Pubblicazione","I contenuti possono essere pubblicati sui canali ufficiali dell’organizzazione e conservati per il periodo necessario alle finalità di documentazione e comunicazione. Le modalità concrete dipendono dal tipo di contenuto e dal contesto in cui è stato realizzato."],
    ["6. Richieste","Per segnalazioni relative a una fotografia o a una ripresa è possibile contattare infinityeventsit@gmail.com, indicando, quando possibile, evento, data, contenuto interessato e richiesta. La richiesta sarà valutata in base al contesto e alla base giuridica applicabile."],
    ["7. Contenuti di terzi","La ripubblicazione o l’utilizzo di contenuti realizzati autonomamente da partecipanti o terzi non è automaticamente autorizzata da Infinity Events. Restano applicabili i diritti degli autori e delle persone rappresentate."]
  ]},
  {id:"reports",icon:Mail,title:"Report e comunicazioni",text:[
    ["1. Report operativi","Infinity EventOS può generare report periodici relativi a ticket venduti, partecipanti, accessi, braccialetti, transazioni e altri dati operativi disponibili per lo specifico evento."],
    ["2. Destinatari","I report sono destinati agli utenti autorizzati dall’organizzazione e vengono inviati agli indirizzi configurati per la reportistica dell’evento."],
    ["3. Frequenza","La reportistica può essere configurata come report periodico, inclusi report settimanali quando la funzione è attiva. La frequenza e l’invio possono essere modificati o disattivati dagli utenti autorizzati secondo le funzionalità disponibili."],
    ["4. Contenuto","Il report può contenere dati aggregati e dettagli operativi necessari alla gestione dell’evento, inclusi dati relativi a biglietti, braccialetti, accessi, ricavi e transazioni, nei limiti delle autorizzazioni dell’utente."],
    ["5. Nessun marketing","I report operativi non costituiscono, nella configurazione attuale, una newsletter commerciale e non sono utilizzati per finalità di marketing."],
    ["6. Nessun tracking email","Secondo la configurazione attuale, l’invio dei report non utilizza sistemi di tracking dell’apertura o del click."],
    ["7. Allegati","Quando il report è generato come documento allegato, il messaggio email può contenere esclusivamente un testo informativo essenziale e il riferimento all’allegato, in modo da mantenere la comunicazione semplice e funzionale."],
    ["8. Contatti","Per problemi relativi a un report, un invio o alla modifica della configurazione è possibile contattare infinityeventsit@gmail.com."]
  ]}
];

function Doc({doc}){return <article className="space-y-7"><div><div className="flex items-center gap-3 text-purple-300"><doc.icon size={20}/><span className="text-xs uppercase tracking-[.18em] font-bold">Documento</span></div><h2 className="text-3xl sm:text-4xl font-bold mt-3">{doc.title}</h2></div>{doc.text.map(([title,body])=><section key={title}><h3 className="text-sm font-semibold text-white mb-2">{title}</h3><p className="text-sm sm:text-[15px] leading-7 text-zinc-400">{body}</p></section>)}</article>}

export default function LegalCenter({compact=false}){
 const [open,setOpen]=useState(compact?"":null);
 const [doc,setDoc]=useState(docs[0]);
 const show=(item)=>{setDoc(item);setOpen("doc")};
 if(compact)return <div className="flex flex-wrap gap-3 text-xs text-zinc-500">{docs.map(item=><button key={item.id} onClick={()=>show(item)} className="hover:text-white transition">{item.title}</button>)}{open&&<div className="fixed inset-0 z-[100] bg-black/75 backdrop-blur-md p-4 sm:p-8 flex items-center justify-center" onMouseDown={(e)=>e.target===e.currentTarget&&setOpen(null)}><div className="w-full max-w-3xl max-h-[88vh] overflow-y-auto rounded-3xl border border-white/10 bg-[#111217] shadow-2xl p-6 sm:p-9"><div className="flex justify-end mb-4"><button onClick={()=>setOpen(null)} className="p-2 rounded-xl bg-white/5 hover:bg-white/10"><X size={18}/></button></div><Doc doc={doc}/></div></div>}</div>;
 return <div className="min-h-screen bg-[#09090B] text-white"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#09090B]/90 backdrop-blur-xl"><div className="max-w-6xl mx-auto px-5 sm:px-8 h-16 flex items-center justify-between"><a href="/dashboard" className="flex items-center gap-3 font-bold"><img src="/favicon.svg" className="w-8 h-8 brightness-0 invert"/><span>Infinity EventOS</span></a><a href="/" className="text-sm text-zinc-400 hover:text-white flex items-center gap-2"><ArrowLeft size={16}/> Dashboard</a></div></header><main className="max-w-6xl mx-auto px-5 sm:px-8 py-12 sm:py-16"><div className="max-w-3xl mb-12"><p className="text-purple-300 text-xs uppercase tracking-[.2em] font-bold">Legal Center</p><h1 className="text-4xl sm:text-6xl font-bold tracking-tight mt-3">Tutto ciò che devi sapere.</h1><p className="text-zinc-400 mt-5 text-base sm:text-lg leading-7">Le informazioni legali e privacy di Infinity EventOS e dei servizi VividFest, raccolte in un unico spazio.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{docs.map(item=><button key={item.id} onClick={()=>show(item)} className="text-left rounded-2xl border border-white/10 bg-white/[.025] hover:bg-white/[.05] hover:border-purple-400/30 p-5 transition group"><div className="w-10 h-10 rounded-xl bg-purple-500/10 text-purple-300 grid place-items-center mb-6"><item.icon size={19}/></div><h2 className="font-semibold">{item.title}</h2><p className="text-xs leading-5 text-zinc-500 mt-2">Apri documento <ChevronRight size={13} className="inline group-hover:translate-x-1 transition-transform"/></p></button>)}</div><div className="mt-10 rounded-2xl border border-amber-400/10 bg-amber-400/[.04] p-5 text-xs leading-6 text-zinc-500"><strong className="text-zinc-300">Nota:</strong> i testi sono la base informativa del progetto e devono essere verificati dal professionista incaricato della compliance prima della pubblicazione definitiva, soprattutto per ruoli dei fornitori, conservazione dei dati e specifiche condizioni dell'evento.</div></main></div>
}
